.gitignore, lcls-twincat-motion/Library/DUTs/DUT_MotionStage.TcDUT, lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
Accepting suggestions for:
1. Better names
2. Other vars to permanently rename before we are locked in
List of renames:
- `bBrake` -> `bBrakeReleased` to indicate polarity
- `bEnabled` -> `bEnableDone` to remove visual confusion with `bEnable` and to make clear the intent of the variable
- `bLimFwd` -> `bLimFwdOk` (and equivalent change on all limit variables) to indicate polarity and status as a permission variable
closes #12
=> API: Rename several confusing vars

screens/detailed_beckhoff_motor.ui, screens/typhos_screen.py, screens/typhos_screen.sh
Add a typhos template for beckhoff motor screens and quick launcher scripts for people who just want a motor suite for quick testing. I'm not 100% sure this is best place for things like this, or if how I did it is even optimal, but here's something.
@ghalym @rajanplumley this is the screen I mentioned today
The template is based off of Teddy's positioner template with minor tweaks and additions.
Example screen called using `typhos_screen.sh IM3L0:PPM:MMS`
=> ENH: Typhos Template and Quick Launcher

lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
Prospective fix for @ghalym 's reported slits motion issues.
The code prior to this PR raises an error if we are:
- At a limit switch
- We try to move past the switch
Because the user should be told of this so they know why the stage didn't move.
However, the consequence of making it an error is that this will lock up the motion until the error is acknowledged and cleared. This means that automation routines (even just "move the slit blades together" routines) need to know to clear errors to make them work reliably, and then we run a risk of automatically clearing other error types that might be more serious. In practice now, this may lead to the state where we ask for the slits to open twice, then some axes get stuck at a limit, so asking the slits to close causes not all the blades to …
=> MNT: reduce at limit error to warning

lcls-twincat-motion/Library/GVLs/MOTION_GVL.TcGVL, lcls-twincat-motion/Library/Library.tmc, lcls-twincat-motion/_Config/PLC/Library.xti
Increase MAX_STATES from 5 to 6, because the WFS has 6 states (Out and 5 targets).
Still unsure on a long-term solution for states devices.
On the Python side we'll probably end up giving in and making different class variants for each state count to optimize the experience/performance at the cost of one-time annoying programming.
On the PLC side we want to minimize the PV count because it improves IOC performance, but I'm not sure the best way. Perhaps we end up allocating max states but finding a way to only generate PVs for the states in use via new pytmc magic.
=> ENH: Add +1 state allocation

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS_Base.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateBase_WithPMPS.TcPOU
The pragma was putting to a lower-level caller that gets overridden in a higher level. This resolves the issue so that the built IOC will set/get from the correct variable.
closes #94
=> MNT: move arbiter pragma so EPICS works

README.md, lcls-twincat-motion/Library/DUTs/DUT_MotionStage.TcDUT, lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/FB_EncSaveRestore.TcPOU, lcls-twincat-motion/Library/POUs/Motion/FB_MotionHoming.TcPOU, lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
Implements the following:
- 5 different homing strategies, accessible via the ~`.HOMF` and `.HOMR` fields~ `:PLC:bHomeCmd` PV
- position save/restore for motors with relative encoders
I'm going to do a writeup here and include much of the information that follows in the README.
To activate a homing routing, put 1 to the EPICS ~`.HOMF` or `.HOMR` fields. As far as the TwinCAT program is concerned, these both mean the same thing: "home using our internal configuration".~ `:PLC:bHomeCmd` PV.
To configure a homing routine, set the `fHomePosition` variable to the position to use after homing, and set the `nHomingMode` variable to pick a strategy. These strategies are stored in `ENUM_EpicsHomeCmd` enum. All homing motion strategies move towards their destinations using the "Homing Velocity …
=> ENH: Relative encoder support (homing, saving)

lcls-twincat-motion/Library/GVLs/MOTION_GVL.TcGVL
As we don't have good support for pytmc pragmas that allow for partial inclusion of structures, I believe this is the quickest solution to support AT1K4, with its 8 filter states and 1 out state (and the implied unknown state).
Ref https://github.com/pcdshub/lcls-plc-tmo-motion/pull/39
=> MNT: bump MAX_STATES to 9

lcls-twincat-motion/Library/POUs/Motion/FB_MotionHoming.TcPOU
closes #113 
Simply wait for the axis to stop prior to setting the position to home, to avoid the homing failure where we try to set the position of an axis still in motion.
I reproduced the bug on my test stage, then routed all transitions in the state machine that should wait through a new waiting state. Apply the patch to my test stage, then test the homing- all was well.
This has previously affected the scatter slits and the XTES imager zoom/focus, but this should fix both cases.
=> MNT: add waits where appropriate in the homing routines

lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
closes #121 
Sometimes, the IOC may send "set the cmd to True" twice via screen use- not sure if this is double-clicking with perfect timing, some sort of write queuing, or something else. This breaks the session because I was only resetting the homing command on rising edge.
This maintains the "start homing on rising edge" behavior, but it allows the command to reset and be re-issued even if this double-put happens.
=> FIX: Always reset command PVs

README.md
15 states = 9 states now, but really `MOTION_GVL.MAX_STATES`
=> DOC: readme state count referred to old value

lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS_Base.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateBase.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateBase_WithPMPS_Test.TcPOU
There are at least ~2~ ~3~ 4 bugs right now related to #123 
This fixes all the known bugs (closes #123)
- If the axis is already moving when we ask for a move, wait for the previous move to truly end before starting again. Otherwise, the new move command just hangs forever.
- Do not start a move if we plan to disable the axis in the next cycle. Also stop a move in this scenario. Otherwise, this throws a confusing error instead of just... stopping.
- Reset missing variables in the bReset of PMPS state moves. Otherwise, these variables can get stuck in strange states after errors or when interrupting moves.
- Do not fully reset the state FB when we interrupt it with a new move, this actually breaks everything and causes confusing errors.
Also:
- Fix testing bug in the pmps tester fb
=> ENH: fix issues with interrupting state moves

lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
Follow-up to #125 
We check `bSafetyReady` on the start of a new move request to see if we should enable the motor yet.
However, if we were in the middle of an active move, then get a new move request, this block of code can actually disable the enabled motor, causing an error.
This PR changes the "moving" blocks here to only be able to enable the motor, not disable it.
This is the last piece needed for #123 
The homing enable is untouched because I don't want to test it during a PAMM.
There is other code later in this function block intended to handle the motor disabling.
=> MNT: fix issue where auto-enable block could disable

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS.TcPOU
See https://github.com/pcdshub/lcls-twincat-pmps/pull/91
Will test after next pmps tag before merging.
=> ENH: pass the motor name to the arbiter via new bptm argument

lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut_WithPMPS.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStateInOut_WithPMPS_Test.TcPOU
Sets in and out state names for the "example" state positioners (which are used in production).
Closes #144 
Not yet tested.
Issue and PR text.
=> FIX: set stIn/stOut names for in/out state positioners

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateBase_WithPMPS.TcPOU
`FB_PositionStatePMPS(FB)` function block currently doesn't allow for  `i_xAutoReset` to be set to `True` causing all position state PMPS motion systems to require a manual reset. Here we add an input variable `bAutoReset` that defaults to `False`. PMPS states can now be implemented as FFO auto resetting.
Users have to currently auto clear faults on MR1L0 and MR2L0 to permit beam.
Not tested yet.
=> ENH: add option for auto clearing beam parameter mismatch fast faults

lcls-twincat-motion/Library/POUs/Motion/FB_MotionPneumaticActuator.TcPOU
Adding the option to auto reset FFO for pneumatic actuators.
ST1K4 in TMO is a photon stopper that has a pneumatic actuator. The FFO is latching, so when the actuator is retracted, operators still need to go to the PMPS screen to Ack the fault. This way, when instantiating the function block and setting the i_xAutoreset bit to True, they don't need to Ack the fault from the PMPS diagnostics screen.
=> DEV: Adding the option to auto reset FFO for pneumatic actuators.

lcls-twincat-motion/Library/GVLs/MOTION_GVL.TcGVL
Allow all 15 states to be used (and create PVs for their configurations)
TMO needs all of the states to handle the spectrometer
Previously, this was limited to reduce clutter on the typhos GUI (among other things). This is no longer an issue.
Right click project -> check all objects to ensure no syntax errors
Comments + release notes
=> ENH: increase MAX_STATES to the EPICS max for TMO spec

lcls-twincat-motion/Library/DUTs/DUT_MotionPneumaticActuator.TcDUT
`DUT_MotionPneumaticActuator` has a miss spelled pragma for the PV: bInsertDigitalOutput
typo, fix, insert 'r'
devices can't connect with this typo as the PV will be wrong.
https://github.com/pcdshub/pcdsdevices/pull/1088
This typo was found while testing `pneumatic.py` 
The pneumatic device can access the PV with the typo.
=> BUG: inset -> insert

lcls-twincat-motion/Library/GVLs/MOTION_GVL.TcGVL, lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS.TcPOU, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_PositionStatePMPS_Base.TcPOU, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_Standard_PMPSDB.TcPOU, lcls-twincat-motion/Library/Version/Global_Version.TcGVL
1. Remove the deprecated MAX_STATES backcompat.
2. Allow a pmps state mover to swap out and transition to new pre-emptive beam states without a physical move, so long as the new beam state has a unique ID.
3. Fixed the inverted logic for the unknown state FFO.
4. Fix a bug where database reads would be immediately overwritten instead of used.
5. Add pytmc pragmas to let us inspect which specific parameters have been loaded for a state mover.
6. Style updates
7. Automatic build changes in Global_Version.TcGVL
1. The MAX_STATES backcompat was causing compilation problems on projects that did not explicitly refer to `lcls-twincat-general`.
2. Soon, we will need to implement "WFS" mode for certain imagers, which decreases the required beam level needed. This should happen in-place when the …
=> FIX: Fixes for soft-line deployment

lcls-twincat-motion/Library/DUTs/DUT_MotionStage.TcDUT, lcls-twincat-motion/Library/POUs/Motion/Utils/FB_SetEnables.TcPOU
Added EPS structures in DUT_MotionStage for Forward, Backward, and Power EPS interlock information and logic. In FB_SetEnables a new condition of EPS_OK is added for its respective structure instead of using limit switches.
[ Jira Issue
](https://jira.slac.stanford.edu/browse/LCLSPC-373)
A PLC Program was created using the modified motion library to test if bAllForward, bAllBackward Enable values changed when EPS structure was false.
=> ENH: EPS structures in DUT_MotionStage for interlock information and logic

lcls-twincat-motion/Library/Library.tmc, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_Standard_PMPSDB.TcPOU, lcls-twincat-motion/_Config/PLC/Library.xti
- Add `VAR_OUT` `BOOL` `bReadPmpsDb` to `FB_Standard_PMPSDB`
- Set it high for once when `fbPmpsFileReader.bBusy` is finished.
- Creates a handle to trigger a reload of pmps database parameters not in state implementation
https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=368318178
Asks for hard coded beam parameters to be loaded from the JSON doc.
This was tested using lcls-plc-tmo-optics/pull/35
https://github.com/pcdshub/lcls-plc-tmo-optics/pull/35
https://github.com/pcdshub/lcls-twincat-optics/pull/18
=> Add VAR_OUTPUT triggered after a read of MOTION_GVL.fbPmpsFileReader

lcls-twincat-motion/Library/DUTs/ST_MotionStage.TcDUT
Shorten EPS pvs.
stEPSForwardEnable -> stEPSF
stEPSBackwardEnable -> stEPSB
stEPSPowerEnable  -> stEPSP
Long PV names was stopping IOC from being build. 
'ERROR:pytmc.bin.db:Records exceeding the maximum length of 60 were found:'
=> shorten  stEPSForwardEnable structs PVs 

lcls-twincat-motion/Library/DUTs/ST_MotionStage.TcDUT, lcls-twincat-motion/Library/DUTs/ST_PositionState.TcDUT
https://docs.google.com/spreadsheets/d/1xfSB1mJwVu4tXvxBT85TEYVi29Z7VoQ4w5CXw13rV8A/edit#gid=0
> Due to issues with PV count and long boot times in the TMO plc motion IOC, I'm planning to remove a bunch of PVs from the twincat motion library. This should improve the boot time for all the other beckhoff motion IOCs too
N/a, hopefully the pragma lint CI passes
Google doc and release notes
=> API: remove many unused PVs that scale with motor/state counts

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_MotionReadPMPSDBND.TcPOU, lcls-twincat-motion/Library/Tests/FB_MotionReadPMPSDBND_Test.TcPOU, lcls-twincat-motion/_Config/PLC/Library.xti
- Fix the bug described in  issue 194  (closes #194)
- Add a test for this case
- Augment the existing test cases with a specific error message for each loop iteration. If you don't do this, they count as duplicate checks and are skipped.
- Most TMO motion devices are currently stuck
- Unit test only
- Works in TMO running the dev build
This PR text + later release notes
=> FIX: fix bug related to half-full state allocations

lcls-twincat-motion/Library/POUs/Motion/Utils/F_MotionErrorCodeLookup.TcPOU
- Add error messages from issue texts
- Add a placeholder message for when we need to make fake testing errors
- closes #152 
- closes #199 
- I accidentally made a fake error today that matched a real error code
I did the "check all objects" syntax check, I didn't go back and try to cause these specific error flavors, nor did I think this required a unit test.
Just this PR for now, later in the release notes
=> ENH: add some more error messages for motors

lcls-twincat-motion/Library/POUs/Motion/States/FB_StatesInputHandler.TcPOU, lcls-twincat-motion/Library/Tests/FB_PositionStateND_Test.TcPOU, lcls-twincat-motion/_Config/PLC/Library.xti
When the user resets an error, bring the states input handler FB back to a known state.
Will close #197 
In short: previously, we could get into a deadlocked state where the input FB would always keep bExecute high, which means the move FB would never be able to get a rising edge.
- Unit test that fails before and passes afterwards
- Interactive testing with the example motion plc code
Detailed documentation in the unit test
=> FIX: addressing the state input deadlock bug

lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateND_Core.TcPOU
Calling read/move requires fb internal to be called first, but somehow the ordering was wrong
Ends up making the pmps states devices come up in a "transition" state always because the PLC can't check that they are at the correct state during the first cycle
Currently testing using my kfe motion PR
n/a
=> FIX: run fbInternal first to mark states as ready to use

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_MotionBPTM.TcPOU
A fast fault can be reset on a rising trigger to the reset input
Previously, the code would never bring this input back to low, it would stay high
Therefore, the fault could only be reset once
Permanent fast faults are bad
closes #202 
Interactively in kfe motion, and:
n/a
=> FIX: some fast faults could only be reset once due to rt detection

lcls-twincat-motion/Library/DUTs/E_LCLSMotionError.TcDUT, lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/FB_MotionRequest.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateMove.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_PositionStateND_Core.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/FB_StatesInputHandler.TcPOU, lcls-twincat-motion/Library/POUs/Motion/Utils/F_MotionErrorCodeLookup.TcPOU, lcls-twincat-motion/Library/Tests/FB_PositionStateMove_Test.TcPOU, lcls-twincat-motion/_Config/PLC/Library.xti
- If there is a move error, cut the execute output
- Require a bExecute rising edge and bAllowMoves at the same time, or else no state moves
See https://jira.slac.stanford.edu/browse/ECS-3932
There are cases where "unsafe" moves can become marked as "safe" during execution, and then immediately start as if they were waiting to become "safe" rather than cancelling the move request altogether.
I created a unit test that follows the following sequence:
- Ask for a move to a `bMoveOk = FALSE` state
- Confirm no move
- Set `bMoveOk := TRUE`
- Confirm no move
- Reset the error
- Confirm no move
- Ask for a new move
- Confirm yes move
I also tested this interactively, and it works as one would expect: you need to reset the error, wait for the move to become safe, and then explicitly ask for the …
=> FIX: issues relating to "queued" moves in state mover with bMoveOk

lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionState1D_InOut.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionState2D_InOut.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStatePMPS1D_InOut.TcPOU, lcls-twincat-motion/Library/POUs/Motion/States/Examples/FB_PositionStatePMPS2D_InOut.TcPOU, lcls-twincat-motion/_Config/PLC/Library.xti
Reverse IN and OUT indices for the example state FBs to match the enum, because if the order is wrong then IN sends us to OUT and vice versa.
See https://github.com/pcdshub/lcls-twincat-motion/blob/master/lcls-twincat-motion/Library/DUTs/E_EpicsInOut.TcDUT
closes #208 
Fixes the remaining issue in https://github.com/pcdshub/lcls-plc-kfe-rix-motion/pull/61
only here
=> BUG: reverse the in/out order in the in/out example fbs to match their enum

lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/States/FB_StatesInputHandler.TcPOU, lcls-twincat-motion/Library/Tests/FB_TestStateInitTiming.TcPOU, lcls-twincat-motion/Library/Tests/PRG_TEST.TcPOU, lcls-twincat-motion/_Config/NC/Axes/Axis_TestStateInitTiming.xti, lcls-twincat-motion/_Config/NC/NC.xti, lcls-twincat-motion/_Config/PLC/Library.xti, lcls-twincat-motion/lcls-twincat-motion.tsproj
There is a bad state that can happen at PLC startup when we initialize the states FBs. This is done using the first cycle positions which are not guaranteed to be initialized at that point. The impact of this bad state is essentially a fast fault until the first move or reset command: "Invalid goal position in state move"
The solution here is to allow the states FB to re-initialize on the fly when the read state changes. This is implemented by caching the previous cycle's read state, and re-doing the "current goal" initialization if we are idle and the state has updated.
https://jira.slac.stanford.edu/browse/ECS-4486
This PR adds a test case that was failing prior to the PR and passing after it.
I need to get permission to test this from one of the following POCs/projects:
Josh - …
=> BUG: fix "invalid goal position" fast fault initialization bug

lcls-twincat-motion/Library/DUTs/ST_AxisParameterSetExposed.TcDUT, lcls-twincat-motion/Library/DUTs/ST_MotionStage.TcDUT, lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/FB_MotionStageNCParams.TcPOU, lcls-twincat-motion/Library/Tests/FB_AxisParameterSetExposed_Test.TcPOU, lcls-twincat-motion/Library/Tests/PRG_TEST.TcPOU, lcls-twincat-motion/_Config/NC/Axes/Axis_AxisParameter_Test.xti, lcls-twincat-motion/_Config/NC/NC.xti, lcls-twincat-motion/_Config/PLC/Library.xti, lcls-twincat-motion/lcls-twincat-motion.tsproj
Created a new DUT called ST_AxisParameterSetExposed.
Added the new DUT as a member of ST_MotionStage.
Added logic to FB_MotionStage to copy the exposed parameters into the new DUT whenever the stAxisParameters structure is updated.
Added pytmc pragmas to the ST_AxisParameterSetExposed to populate the new PVs when an IOC is built using lcls-twincat-motion.
This new feature came up as a result of difficulties with scientists and other staff in understanding why certain motions cause errors or are not allowed to be completed. With these parameters exposed, they will have greater transparency with understanding the limits of the system that have been programmed into the PLC.
A new unit test was added to test that the values are being copied properly.
All the previous unit tests and the new …
=> Implemented Changes to Expose Axis Parameters as READ-ONLY to EPICS

lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_Standard_PMPSDB.TcPOU
Use the IPCDiag FBs to check the PLC's OS, then use that OS to decide the default directory for pmpsdb reading.
These function blocks are somewhat strange, but I followed the docs closely and arrived at this implementation.
Here, I've set the new default directory for TwinCAT BSD PLCs to match the associated PRs:
https://github.com/pcdshub/twincat-bsd-ansible/pull/19
https://github.com/pcdshub/pmpsdb_client/pull/25
And I've left the default directory for other PLC types unchanged.
We can explicitly set a directory for the PMPS database loading in each project, but this leaves open the possibility for typos and copy/paste errors. The directory should be the same every time (dependent on OS), so we can directly check the OS to set a reasonable default. The code is skipped entirely if the …
=> ENH: check PLC OS to set new default dir for BSD PLCs

README.md
=> Fix typo in Readme that got merged in Bug ecs 4719 PR

.gitignore, lcls-twincat-motion.sln, lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/FB_MotionVirtualFrame.TcPOU, lcls-twincat-motion/Library/Tests/FB_MotionVirtualFrame_Test.TcPOU, lcls-twincat-motion/Library/Tests/Helpers/FB_MotionStageSetAndMoveHelper.TcPOU, lcls-twincat-motion/Library/Tests/Helpers/FB_MotionStageSetHelper.TcPOU, lcls-twincat-motion/Library/Tests/PRG_TEST.TcPOU, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameRx_Test.xti, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameRy_Test.xti, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameRz_Test.xti, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameVx_Test.xti, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameVy_Test.xti, lcls-twincat-motion/_Config/NC/Axes/Axis_MotionVirtualFrameVz_Test.xti, lcls-twincat-motion/_Config/NC/NC.xti, lcls-twincat-motion/_Config/PLC/Library.xti, lcls-twincat-motion/lcls-twincat-motion.tsproj
- Added a function block called FB_MotionVirtualFrame which takes:
- 3 ST_MotionStages representing real axes that are orthogonal to each other and in a base frame of reference.
- And 3 ST_MotionStages representing virtual axes that are orthogonal to each other and in a new frame of reference.
- Using these motion stages, it computes the transformation from a base frame of reference to a new frame of reference using 3 euler angles and a rotation order as inputs. By default, the order and angles are interpreted as going from the base to the virtual frame. This can be switched to go from virtual to base frame of reference.
- This function block has two modes of operation. If enabled, this function block will automatically handle commanding the real axes to move when the virtual axes are …
=> Add motion virtual frame

lcls-twincat-motion/Library/Library.plcproj, lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU, lcls-twincat-motion/Library/Tests/FB_PowerEnableMode_Test.TcPOU, lcls-twincat-motion/Library/Tests/PRG_TEST.TcPOU, lcls-twincat-motion/_Config/NC/Axes/Axis_PowerEnableMode_Test.xti, lcls-twincat-motion/_Config/NC/NC.xti, lcls-twincat-motion/_Config/PLC/Library.xti
Reset Drive Power after a mode transition of "EnableMode" from 'ALWAYS' to 'DURING_MOTION' 
Bug fix: The motion library does not remove power on the drive when mode switches from ALWAYS to 'DURING_MOTION'. this start motion in an unsafe condition as 'DURING_MOTION' should first enable power to drive and then execute the motion request.
Code Tested on TwinCAT 4026.11 under TcBSD PLC running TwinCAT 4026 connected to a Renishaw absolute stage with an EL7031 drive. Library Units Test were successfully run. The feature functionality tests consisted of setting the enable mode to 'ALWAYS' verifying that power was enabled in all directions then resetting the enable mode to 'DURING_MOTION' and observed that power was removed to the drive in all direction. Move request in this mode would then …
=> Reset Drive Enable Mode after mode transition

lcls-twincat-motion/Library/POUs/Motion/FB_MotionStage.TcPOU
Implement warning message when the axis homing mode is assigned and the bHomed flag is not set before attempting to move the axis
EPICS side complains while an axis with homing mode defined, but bHomed is not set. in other words, no homing routine was executed for this axis before an absolute move was requested.
Code Tested on TwinCAT 4026.11 running in Local Mode under VM.  A warning message in printed in the error message window each time an absolute move is performed on the axis while bHomed is unset to notify the operator. this notification will be reset once the axis is homed.
Descriptive comments were added above the implementation line in the modified FBs.
=> Warning Message for unset bHomed Flag for a Home mode defined stage

lcls-twincat-motion/Library/POUs/Motion/PMPS/FB_MiscStatesErrorFFO.TcPOU
- Making the debouncer fast fault auto-reset
- nTripCount now has a maximum value of 5, so that it does not grow larger than that and delay beam while it ticks down
https://jira.slac.stanford.edu/browse/ECS-7551
=> Debouncer autoreset and counter max limit
